[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true }
rand = { workspace = true }
renet = { workspace = true }
socket2 = "0.6.1"
strum = { version = "0.27", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }